# Generated by Django 6.0.3 on 2026-04-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/image')),
                ('unit', models.CharField(choices=[('l', 'Lits'), ('piece', 'Dona'), ('box', 'Quti')], default='pieace')),
                ('amount', models.IntegerField()),
                ('category', models.ManyToManyField(related_name='products', to='ombor.category')),
            ],
        ),
    ]
