# Generated by Django 6.0.3 on 2026-04-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_workers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default='1', max_length=25),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_sum',
            field=models.CharField(max_length=50),
        ),
    ]
