# Generated by Django 6.0.3 on 2026-04-11 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_salary_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='hr.workers'),
        ),
    ]
