# Generated by Django 6.0.3 on 2026-04-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ombor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('T', "Ta'minotchi"), ('M', 'Mijoz')])),
            ],
        ),
        migrations.CreateModel(
            name='Product_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in', to='ombor.product')),
                ('reciewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recievers', to='hamkorlar.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Product_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField()),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamkorlar.partner')),
                ('product', models.ManyToManyField(related_name='products_out', to='ombor.product')),
            ],
        ),
    ]
