# Generated by Django 6.0.3 on 2026-04-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamkorlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(max_length=40),
        ),
    ]
