# Generated by Django 6.0.3 on 2026-04-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamkorlar', '0002_alter_partner_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_in',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product_out',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product_out',
            name='summa',
            field=models.CharField(max_length=50),
        ),
    ]
